version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_ENDPOINT=${GEMINI_ENDPOINT}
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
